[workspace]
members = [
    "trait-variant",
    "trait-transformer",
]

resolver = "2"

[workspace.package]
repository = "https://github.com/Sherlock-Holo/impl-trait-utils"
license = "MIT OR Apache-2.0"
