name: CI

on:
  push:
    branches: [ "trait-make" ]
  pull_request:
    branches: [ "trait-make" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --locked --verbose
    - name: Run tests
      run: cargo test --locked --verbose
